2024-10-02 10:39:09,270 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\pythonProject12(юнит_тест)\tests_12_4.py", line 81, in test_run
    runner = Runner(25, 10)
             ^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\pythonProject12(юнит_тест)\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-02 10:39:09,271 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\pythonProject12(юнит_тест)\tests_12_4.py", line 69, in test_walk
    runner = Runner('walker', -15)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\pythonProject12(юнит_тест)\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -15
